language: node_js
before_install:
  - npm -g install npm@latest
matrix:
  include:
    - node_js: "6.0"
      script:
        - npm test
    - node_js: "0.12"
      script:
        - npm test
    - node_js: "0.11"
      script:
        - npm test
    - node_js: "0.10"
      script:
        - npm test
notifications:
  email: false
